version: '3.3'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    environment:
      - DATABASE_URL=postgresql://user:password@db/prod_db
      - JWT_SECRET_KEY=your_secret_key
    volumes:
      - .:/app
    depends_on:
      - db

  db:
    image: postgres:13
    environment:
      POSTGRES_DB: prod_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - pgdata:/var/lib/postgresql/data

  test:
    build: .
    command: pytest
    environment:
      - DATABASE_URL=postgresql://user:password@db/prod_db
      - JWT_SECRET_KEY=your_secret_key
    depends_on:
      - db

volumes:
  pgdata:
